<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped Keyed and DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/{Keyed,DefInjected}/**/*.xml key. For a Keyed key, English
  comes from the matching Mod/Languages/English/Keyed file. For a DefInjected key (only
  MainButtonDef/FGP_Settings here, label and description), the mod ships no English
  DefInjected override: English is the native field read straight from Mod/Defs/MainButtons.xml,
  the same value the game falls back to. This is why the file is built by a script, not by
  hand: the fallback path differs key by key, and a hand-copy cannot be trusted not to drift.

  This mod has no source in another language: it was written directly in English and French,
  not ported. Original equals English throughout, stated once here rather than on every row
  (TRANSLATIONS.md, "Systematic French review", the Original column rule).
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Resolve-DefField($defsRoot, [string]$key) {
    # key looks like "DefName.field"
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    if (-not $script:defCache.ContainsKey($defName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//*[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$defName] = $found
    }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    $cur = $node
    foreach ($p in $rest) {
        if ($null -eq $cur) { return $null }
        $cur = $cur.$p
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$englishRoot = Join-Path $Root 'Mod/Languages/English'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``_tools/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** This mod has no source in another")
[void]$out.AppendLine("language; it was written directly in English and French, not ported.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree after pass 2b (23a392e).")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $en = $null
        if ($enEntries.Contains($key)) { $en = $enEntries[$key] }
        else { $en = Resolve-DefField $defsRoot $key }
        if ($null -eq $en) { $en = '*(not found — check by hand)*' }
        $orig = $en
        $flag = if ($fr -match '\?\?\?|TODO') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
